//! DO NOT EDIT
//! GENERATED BY src/tools/config_gen.zig

const std = @import("std");

pub const Builtin = struct {
    return_type: []const u8,
    documentation: []const u8,
    parameters: []const Parameter,

    pub const Parameter = struct {
        signature: []const u8,
        documentation: ?[]const u8,
    };
};

pub const builtins: std.StaticStringMap(Builtin) = .initComptime(&[_]struct { []const u8, Builtin }{
    .{
        "@addrSpaceCast",
        .{
            .return_type = "anytype",
            .documentation =
            \\Converts a pointer from one address space to another. The new address space is inferred based on the result type. Depending on the current target and address spaces, this cast may be a no-op, a complex operation, or illegal. If the cast is legal, then the resulting pointer points to the same memory location as the pointer operand. It is always valid to cast a pointer between the same address spaces.
            ,
            .parameters = &.{
                .{
                    .signature = "ptr: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@addWithOverflow",
        .{
            .return_type = "struct { @TypeOf(a, b), u1 }",
            .documentation =
            \\Performs `a + b` and returns a tuple with the result and a possible overflow bit.
            ,
            .parameters = &.{
                .{
                    .signature = "a: anytype",
                    .documentation = null,
                },
                .{
                    .signature = "b: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@alignCast",
        .{
            .return_type = "anytype",
            .documentation =
            \\`ptr` can be `*T`, `?*T`, or `[]T`. Changes the alignment of a pointer. The alignment to use is inferred based on the result type.
            \\
            \\A [pointer alignment safety check](https://ziglang.org/documentation/master/#Incorrect-Pointer-Alignment) is added to the generated code to make sure the pointer is aligned as promised.
            ,
            .parameters = &.{
                .{
                    .signature = "ptr: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@alignOf",
        .{
            .return_type = "comptime_int",
            .documentation =
            \\This function returns the number of bytes that this type should be aligned to for the current target to match the C ABI. When the child type of a pointer has this alignment, the alignment can be omitted from the type.
            \\
            \\```zig
            \\const assert = @import("std").debug.assert;
            \\comptime {
            \\    assert(*u32 == *align(@alignOf(u32)) u32);
            \\}
            \\```
            \\The result is a target-specific compile time constant. It is guaranteed to be less than or equal to [@sizeOf(T)](https://ziglang.org/documentation/master/#sizeOf).
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@as",
        .{
            .return_type = "T",
            .documentation =
            \\Performs [Type Coercion](https://ziglang.org/documentation/master/#Type-Coercion). This cast is allowed when the conversion is unambiguous and safe, and is the preferred way to convert between types, whenever possible.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "expression",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@atomicLoad",
        .{
            .return_type = "T",
            .documentation =
            \\This builtin function atomically dereferences a pointer to a `T` and returns the value.
            \\
            \\`T` must be a pointer, a `bool`, a float, an integer, an enum, or a packed struct.
            \\
            \\`AtomicOrder` can be found with `@import("std").lang.AtomicOrder`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "ptr: *const T",
                    .documentation = null,
                },
                .{
                    .signature = "comptime ordering: AtomicOrder",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@atomicRmw",
        .{
            .return_type = "T",
            .documentation =
            \\This builtin function dereferences a pointer to a `T` and atomically modifies the value and returns the previous value.
            \\
            \\`T` must be a pointer, a `bool`, a float, an integer, an enum, or a packed struct.
            \\
            \\`AtomicOrder` can be found with `@import("std").lang.AtomicOrder`.
            \\
            \\`AtomicRmwOp` can be found with `@import("std").lang.AtomicRmwOp`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "ptr: *T",
                    .documentation = null,
                },
                .{
                    .signature = "comptime op: AtomicRmwOp",
                    .documentation = null,
                },
                .{
                    .signature = "operand: T",
                    .documentation = null,
                },
                .{
                    .signature = "comptime ordering: AtomicOrder",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@atomicStore",
        .{
            .return_type = "void",
            .documentation =
            \\This builtin function dereferences a pointer to a `T` and atomically stores the given value.
            \\
            \\`T` must be a pointer, a `bool`, a float, an integer, an enum, or a packed struct.
            \\
            \\`AtomicOrder` can be found with `@import("std").lang.AtomicOrder`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "ptr: *T",
                    .documentation = null,
                },
                .{
                    .signature = "value: T",
                    .documentation = null,
                },
                .{
                    .signature = "comptime ordering: AtomicOrder",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@bitCast",
        .{
            .return_type = "anytype",
            .documentation =
            \\Converts a value of one type to another type. The return type is the inferred result type.
            \\
            \\Asserts that `@sizeOf(@TypeOf(value)) == @sizeOf(DestType)`.
            \\
            \\Asserts that `@typeInfo(DestType) != .pointer`. Use `@ptrCast` or `@ptrFromInt` if you need this.
            \\
            \\Can be used for these things for example:
            \\
            \\ - Convert `f32` to `u32` bits
            \\ - Convert `i32` to `u32` preserving twos complement
            \\Works at compile-time if `value` is known at compile time. It's a compile error to bitcast a value of undefined layout; this means that, besides the restriction from types which possess dedicated casting builtins (enums, pointers, error sets), bare structs, error unions, slices, optionals, and any other type without a well-defined memory layout, also cannot be used in this operation.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@bitOffsetOf",
        .{
            .return_type = "comptime_int",
            .documentation =
            \\Returns the bit offset of a field relative to its containing struct.
            \\
            \\For non [packed structs](https://ziglang.org/documentation/master/#packed-struct), this will always be divisible by `8`. For packed structs, non-byte-aligned fields will share a byte offset, but they will have different bit offsets.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_name: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@bitSizeOf",
        .{
            .return_type = "comptime_int",
            .documentation =
            \\This function returns the number of bits it takes to store `T` in memory if the type were a field in a packed struct/union. The result is a target-specific compile time constant.
            \\
            \\This function measures the size at runtime. For types that are disallowed at runtime, such as `comptime_int` and `type`, the result is `0`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@branchHint",
        .{
            .return_type = "void",
            .documentation =
            \\Hints to the optimizer how likely a given branch of control flow is to be reached.
            \\
            \\`BranchHint` can be found with `@import("std").lang.BranchHint`.
            \\
            \\This function is only valid as the first statement in a control flow branch, or the first statement in a function.
            ,
            .parameters = &.{
                .{
                    .signature = "hint: BranchHint",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@breakpoint",
        .{
            .return_type = "void",
            .documentation =
            \\This function inserts a platform-specific debug trap instruction which causes debuggers to break there. Unlike for `@trap()`, execution may continue after this point if the program is resumed.
            \\
            \\This function is only valid within function scope.
            ,
            .parameters = &.{},
        },
    },
    .{
        "@mulAdd",
        .{
            .return_type = "T",
            .documentation =
            \\Fused multiply-add, similar to `(a * b) + c`, except only rounds once, and is thus more accurate.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "a: T",
                    .documentation = null,
                },
                .{
                    .signature = "b: T",
                    .documentation = null,
                },
                .{
                    .signature = "c: T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@byteSwap",
        .{
            .return_type = "T",
            .documentation =
            \\`@TypeOf(operand)` must be an integer type or an integer vector type with bit count evenly divisible by 8.
            \\
            \\`operand` may be an [integer](https://ziglang.org/documentation/master/#Integers) or [vector](https://ziglang.org/documentation/master/#Vectors).
            \\
            \\Swaps the byte order of the integer. This converts a big endian integer to a little endian integer, and converts a little endian integer to a big endian integer.
            \\
            \\Note that for the purposes of memory layout with respect to endianness, the integer type should be related to the number of bytes reported by [@sizeOf](https://ziglang.org/documentation/master/#sizeOf) bytes. This is demonstrated with `u24`. `@sizeOf(u24) == 4`, which means that a `u24` stored in memory takes 4 bytes, and those 4 bytes are what are swapped on a little vs big endian system. On the other hand, if `T` is specified to be `u24`, then only 3 bytes are reversed.
            ,
            .parameters = &.{
                .{
                    .signature = "operand: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@bitReverse",
        .{
            .return_type = "T",
            .documentation =
            \\`@TypeOf(anytype)` accepts any integer type or integer vector type.
            \\
            \\Reverses the bitpattern of an integer value, including the sign bit if applicable.
            \\
            \\For example 0b10110110 (`u8 = 182`, `i8 = -74`) becomes 0b01101101 (`u8 = 109`, `i8 = 109`).
            ,
            .parameters = &.{
                .{
                    .signature = "integer: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@offsetOf",
        .{
            .return_type = "comptime_int",
            .documentation =
            \\Returns the byte offset of a field relative to its containing struct.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_name: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@call",
        .{
            .return_type = "anytype",
            .documentation =
            \\Calls a function, in the same way that invoking an expression with parentheses does:
            \\
            \\`@call` allows more flexibility than normal function call syntax does. The `CallModifier` enum is reproduced here:
            ,
            .parameters = &.{
                .{
                    .signature = "modifier: CallModifier",
                    .documentation = null,
                },
                .{
                    .signature = "function: anytype",
                    .documentation = null,
                },
                .{
                    .signature = "args: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@clz",
        .{
            .return_type = "anytype",
            .documentation =
            \\`@TypeOf(operand)` must be an integer type or an integer vector type.
            \\
            \\`operand` may be an [integer](https://ziglang.org/documentation/master/#Integers) or [vector](https://ziglang.org/documentation/master/#Vectors).
            \\
            \\Counts the number of most-significant (leading in a big-endian sense) zeroes in an integer - "count leading zeroes".
            \\
            \\The return type is an unsigned integer or vector of unsigned integers with the minimum number of bits that can represent the bit count of the integer type.
            \\
            \\If `operand` is zero, `@clz` returns the bit width of integer type `T`.
            ,
            .parameters = &.{
                .{
                    .signature = "operand: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@cmpxchgStrong",
        .{
            .return_type = "?T",
            .documentation =
            \\This function performs a strong atomic compare-and-exchange operation, returning `null` if the current value is the given expected value. It's the equivalent of this code, except atomic:
            \\
            \\If you are using cmpxchg in a retry loop, [@cmpxchgWeak](https://ziglang.org/documentation/master/#cmpxchgWeak) is the better choice, because it can be implemented more efficiently in machine instructions.
            \\
            \\`T` must be a pointer, a `bool`, an integer, an enum, or a packed struct.
            \\
            \\`@typeInfo(@TypeOf(ptr)).pointer.alignment` must be `>= @sizeOf(T).`
            \\
            \\`AtomicOrder` can be found with `@import("std").lang.AtomicOrder`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "ptr: *T",
                    .documentation = null,
                },
                .{
                    .signature = "expected_value: T",
                    .documentation = null,
                },
                .{
                    .signature = "new_value: T",
                    .documentation = null,
                },
                .{
                    .signature = "success_order: AtomicOrder",
                    .documentation = null,
                },
                .{
                    .signature = "fail_order: AtomicOrder",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@cmpxchgWeak",
        .{
            .return_type = "?T",
            .documentation =
            \\This function performs a weak atomic compare-and-exchange operation, returning `null` if the current value is the given expected value. It's the equivalent of this code, except atomic:
            \\
            \\```zig
            \\fn cmpxchgWeakButNotAtomic(comptime T: type, ptr: *T, expected_value: T, new_value: T) ?T {
            \\    const old_value = ptr.*;
            \\    if (old_value == expected_value and usuallyTrueButSometimesFalse()) {
            \\        ptr.* = new_value;
            \\        return null;
            \\    } else {
            \\        return old_value;
            \\    }
            \\}
            \\```
            \\If you are using cmpxchg in a retry loop, the sporadic failure will be no problem, and `cmpxchgWeak` is the better choice, because it can be implemented more efficiently in machine instructions. However if you need a stronger guarantee, use [@cmpxchgStrong](https://ziglang.org/documentation/master/#cmpxchgStrong).
            \\
            \\`T` must be a pointer, a `bool`, an integer, an enum, or a packed struct.
            \\
            \\`@typeInfo(@TypeOf(ptr)).pointer.alignment` must be `>= @sizeOf(T).`
            \\
            \\`AtomicOrder` can be found with `@import("std").lang.AtomicOrder`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "ptr: *T",
                    .documentation = null,
                },
                .{
                    .signature = "expected_value: T",
                    .documentation = null,
                },
                .{
                    .signature = "new_value: T",
                    .documentation = null,
                },
                .{
                    .signature = "success_order: AtomicOrder",
                    .documentation = null,
                },
                .{
                    .signature = "fail_order: AtomicOrder",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@compileError",
        .{
            .return_type = "noreturn",
            .documentation =
            \\This function, when semantically analyzed, causes a compile error with the message `msg`.
            \\
            \\There are several ways that code avoids being semantically checked, such as using `if` or `switch` with compile time constants, and `comptime` functions.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime msg: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@compileLog",
        .{
            .return_type = "void",
            .documentation =
            \\This function prints the arguments passed to it at compile-time.
            \\
            \\To prevent accidentally leaving compile log statements in a codebase, a compilation error is added to the build, pointing to the compile log statement. This error prevents code from being generated, but does not otherwise interfere with analysis.
            \\
            \\This function can be used to do "printf debugging" on compile-time executing code.
            ,
            .parameters = &.{
                .{
                    .signature = "...",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@constCast",
        .{
            .return_type = "DestType",
            .documentation =
            \\Remove `const` qualifier from a pointer.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@ctz",
        .{
            .return_type = "anytype",
            .documentation =
            \\`@TypeOf(operand)` must be an integer type or an integer vector type.
            \\
            \\`operand` may be an [integer](https://ziglang.org/documentation/master/#Integers) or [vector](https://ziglang.org/documentation/master/#Vectors).
            \\
            \\Counts the number of least-significant (trailing in a big-endian sense) zeroes in an integer - "count trailing zeroes".
            \\
            \\The return type is an unsigned integer or vector of unsigned integers with the minimum number of bits that can represent the bit count of the integer type.
            \\
            \\If `operand` is zero, `@ctz` returns the bit width of integer type `T`.
            ,
            .parameters = &.{
                .{
                    .signature = "operand: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@cVaArg",
        .{
            .return_type = "T",
            .documentation =
            \\Implements the C macro `va_arg`.
            ,
            .parameters = &.{
                .{
                    .signature = "operand: *VaList",
                    .documentation = null,
                },
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@cVaCopy",
        .{
            .return_type = "VaList",
            .documentation =
            \\Implements the C macro `va_copy`.
            ,
            .parameters = &.{
                .{
                    .signature = "src: *VaList",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@cVaEnd",
        .{
            .return_type = "void",
            .documentation =
            \\Implements the C macro `va_end`.
            ,
            .parameters = &.{
                .{
                    .signature = "src: *VaList",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@cVaStart",
        .{
            .return_type = "VaList",
            .documentation =
            \\Implements the C macro `va_start`. Only valid inside a variadic function.
            ,
            .parameters = &.{},
        },
    },
    .{
        "@divExact",
        .{
            .return_type = "T",
            .documentation =
            \\Exact division. Caller guarantees `denominator != 0` and `@divTrunc(numerator, denominator) * denominator == numerator`.
            \\
            \\ - `@divExact(6, 3) == 2`
            \\ - `@divExact(a, b) * b == a`
            \\For a function that returns a possible error code, use `@import("std").math.divExact`.
            ,
            .parameters = &.{
                .{
                    .signature = "numerator: T",
                    .documentation = null,
                },
                .{
                    .signature = "denominator: T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@divFloor",
        .{
            .return_type = "T",
            .documentation =
            \\Floored division. Rounds toward negative infinity. For unsigned integers it is the same as `numerator / denominator`. Caller guarantees `denominator != 0` and `!(@typeInfo(T) == .int and T.is_signed and numerator == std.math.minInt(T) and denominator == -1)`.
            \\
            \\ - `@divFloor(-5, 3) == -2`
            \\ - `(@divFloor(a, b) * b) + @mod(a, b) == a`
            \\For a function that returns a possible error code, use `@import("std").math.divFloor`.
            ,
            .parameters = &.{
                .{
                    .signature = "numerator: T",
                    .documentation = null,
                },
                .{
                    .signature = "denominator: T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@divTrunc",
        .{
            .return_type = "T",
            .documentation =
            \\Truncated division. Rounds toward zero. For unsigned integers it is the same as `numerator / denominator`. Caller guarantees `denominator != 0` and `!(@typeInfo(T) == .int and T.is_signed and numerator == std.math.minInt(T) and denominator == -1)`.
            \\
            \\ - `@divTrunc(-5, 3) == -1`
            \\ - `(@divTrunc(a, b) * b) + @rem(a, b) == a`
            \\For a function that returns a possible error code, use `@import("std").math.divTrunc`.
            ,
            .parameters = &.{
                .{
                    .signature = "numerator: T",
                    .documentation = null,
                },
                .{
                    .signature = "denominator: T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@embedFile",
        .{
            .return_type = "*const [N:0]u8",
            .documentation =
            \\This function returns a compile time constant pointer to null-terminated, fixed-size array with length equal to the byte count of the file given by `path`. The contents of the array are the contents of the file. This is equivalent to a [string literal](https://ziglang.org/documentation/master/#String-Literals-and-Unicode-Code-Point-Literals) with the file contents.
            \\
            \\`path` is absolute or relative to the current file, just like `@import`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime path: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@enumFromInt",
        .{
            .return_type = "anytype",
            .documentation =
            \\Converts an integer into an [enum](https://ziglang.org/documentation/master/#enum) value. The return type is the inferred result type.
            \\
            \\Attempting to convert an integer with no corresponding value in the enum invokes safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior). Note that a [non-exhaustive enum](https://ziglang.org/documentation/master/#Non-exhaustive-enum) has corresponding values for all integers in the enum's integer tag type: the `_` value represents all the remaining unnamed integers in the enum's tag type.
            ,
            .parameters = &.{
                .{
                    .signature = "integer: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@errorFromInt",
        .{
            .return_type = "anyerror",
            .documentation =
            \\Converts from the integer representation of an error into [The Global Error Set](https://ziglang.org/documentation/master/#The-Global-Error-Set) type.
            \\
            \\It is generally recommended to avoid this cast, as the integer representation of an error is not stable across source code changes.
            \\
            \\Attempting to convert an integer that does not correspond to any error results in safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "value: @Int(.unsigned, @bitSizeOf(anyerror))",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@errorName",
        .{
            .return_type = "[:0]const u8",
            .documentation =
            \\This function returns the string representation of an error. The string representation of `error.OutOfMem` is `"OutOfMem"`.
            \\
            \\If there are no calls to `@errorName` in an entire application, or all calls have a compile-time known value for `err`, then no error name table will be generated.
            ,
            .parameters = &.{
                .{
                    .signature = "err: anyerror",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@errorReturnTrace",
        .{
            .return_type = "?*StackTrace",
            .documentation =
            \\If the binary is built with error return tracing, and this function is invoked in a function that calls a function with an error or error union return type, returns a stack trace object. Otherwise returns [null](https://ziglang.org/documentation/master/#null).
            ,
            .parameters = &.{},
        },
    },
    .{
        "@errorCast",
        .{
            .return_type = "anytype",
            .documentation =
            \\Converts an error set or error union value from one error set to another error set. The return type is the inferred result type. Attempting to convert an error which is not in the destination error set results in safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@export",
        .{
            .return_type = "void",
            .documentation =
            \\Creates a symbol in the output object file which refers to the target of
            \\`ptr`.
            \\
            \\`ptr`must point to a global variable or a comptime-known constant.
            \\
            \\This builtin can be called from a [comptime](https://ziglang.org/documentation/master/#comptime) block to conditionally export symbols. When
            \\`ptr`points to a function with the C calling convention and `options.linkage` is `.strong`, this is equivalent to the `export` keyword used on a function:
            \\
            \\This is equivalent to:
            \\
            \\Note that even when using `export`, the `@"foo"` syntax for [identifiers](https://ziglang.org/documentation/master/#Identifiers) can be used to choose any string for the symbol name:
            \\
            \\When looking at the resulting object, you can see the symbol is used verbatim:
            \\
            \\`00000000000001f0 T A function name that is a complete sentence.`
            ,
            .parameters = &.{
                .{
                    .signature = "comptime ptr: *const anyopaque",
                    .documentation = null,
                },
                .{
                    .signature = "comptime options: ExportOptions",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@extern",
        .{
            .return_type = "T",
            .documentation =
            \\Creates a reference to an external symbol in the output object file. T must be a pointer type.
            ,
            .parameters = &.{
                .{
                    .signature = "T: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime options: ExternOptions",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@field",
        .{
            .return_type = "(field)",
            .documentation =
            \\Performs field access by a compile-time string. Works on both fields and declarations.
            ,
            .parameters = &.{
                .{
                    .signature = "lhs: anytype",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_name: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@fieldParentPtr",
        .{
            .return_type = "anytype",
            .documentation =
            \\Given a pointer to a struct or union field, returns a pointer to the struct or union containing that field. The return type (pointer to the parent struct or union in question) is the inferred result type.
            \\
            \\If `field_ptr` does not point to the `field_name` field of an instance of the result type, and the result type has ill-defined layout, invokes unchecked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "comptime field_name: []const u8",
                    .documentation = null,
                },
                .{
                    .signature = "field_ptr: *T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@FieldType",
        .{
            .return_type = "type",
            .documentation =
            \\Given a type and the name of one of its fields, returns the type of that field.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime Type: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_name: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@floatCast",
        .{
            .return_type = "anytype",
            .documentation =
            \\Convert from one float type to another. This cast is safe, but may cause the numeric value to lose precision. The return type is the inferred result type.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@floatFromInt",
        .{
            .return_type = "anytype",
            .documentation =
            \\Converts an integer to the closest floating point representation. The return type is the inferred result type. To convert the other way, use [@round](https://ziglang.org/documentation/master/#round), [@floor](https://ziglang.org/documentation/master/#floor), [@ceil](https://ziglang.org/documentation/master/#ceil), or [@trunc](https://ziglang.org/documentation/master/#trunc). This operation is legal for all values of all integer types.
            ,
            .parameters = &.{
                .{
                    .signature = "int: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@frameAddress",
        .{
            .return_type = "usize",
            .documentation =
            \\This function returns the base pointer of the current stack frame.
            \\
            \\The implications of this are target-specific and not consistent across all platforms. The frame address may not be available in release mode due to aggressive optimizations.
            \\
            \\This function is only valid within function scope.
            ,
            .parameters = &.{},
        },
    },
    .{
        "@hasDecl",
        .{
            .return_type = "bool",
            .documentation =
            \\Returns whether or not a [Namespace](https://ziglang.org/documentation/master/#Namespace) has a declaration matching `name`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime Namespace: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime name: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@hasField",
        .{
            .return_type = "bool",
            .documentation =
            \\Returns whether the field name of a struct, union, or enum exists.
            \\
            \\The result is a compile time constant.
            \\
            \\It does not include functions, variables, or constants.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime name: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@import",
        .{
            .return_type = "anytype",
            .documentation =
            \\Imports the file at `target`, adding it to the compilation if it is not already added. `target` is either a relative path to another file from the file containing the `@import` call, or it is the name of a [module](https://ziglang.org/documentation/master/#Compilation-Model), with the import referring to the root source file of that module. Either way, the file path must end in either
            \\`.zig`(for a Zig source file) or
            \\`.zon`(for a ZON data file).
            \\
            \\If `target` refers to a Zig source file, then `@import` returns that file's [corresponding struct type](https://ziglang.org/documentation/master/#Source-File-Structs), essentially as if the builtin call was replaced by `struct { FILE_CONTENTS }`. The return type is `type`.
            \\
            \\If `target` refers to a ZON file, then `@import` returns the value of the literal in the file. If there is an inferred [result type](https://ziglang.org/documentation/master/#Result-Types), then the return type is that type, and the ZON literal is interpreted as that type ([Result Types](https://ziglang.org/documentation/master/#Result-Types) are propagated through the ZON expression). Otherwise, the return type is the type of the equivalent Zig expression, essentially as if the builtin call was replaced by the ZON file contents.
            \\
            \\The following modules are always available for import:
            \\
            \\ - `@import("std")` - Zig Standard Library
            \\ - `@import("builtin")` - Target-specific information. The command
            \\`zig build-exe --show-builtin`outputs the source to stdout for reference.
            \\ - `@import("root")` - Alias for the root module. In typical project structures, this means it refers back to
            \\`src/main.zig`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime target: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@inComptime",
        .{
            .return_type = "bool",
            .documentation =
            \\Returns whether the builtin was run in a `comptime` context. The result is a compile-time constant.
            \\
            \\This can be used to provide alternative, comptime-friendly implementations of functions. It should not be used, for instance, to exclude certain functions from being evaluated at comptime.
            ,
            .parameters = &.{},
        },
    },
    .{
        "@intCast",
        .{
            .return_type = "anytype",
            .documentation =
            \\Converts an integer to another integer while keeping the same numerical value. The return type is the inferred result type. Attempting to convert a number which is out of range of the destination type results in safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            \\
            \\To truncate the significant bits of a number out of range of the destination type, use [@truncate](https://ziglang.org/documentation/master/#truncate).
            \\
            \\If `T` is `comptime_int`, then this is semantically equivalent to [Type Coercion](https://ziglang.org/documentation/master/#Type-Coercion).
            ,
            .parameters = &.{
                .{
                    .signature = "int: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@intFromBool",
        .{
            .return_type = "u1",
            .documentation =
            \\Converts `true` to `@as(u1, 1)` and `false` to `@as(u1, 0)`.
            ,
            .parameters = &.{
                .{
                    .signature = "value: bool",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@intFromEnum",
        .{
            .return_type = "anytype",
            .documentation =
            \\Converts an enumeration value into its integer tag type. When a tagged union is passed, the tag value is used as the enumeration value.
            \\
            \\If there is only one possible enum value, the result is a `comptime_int` known at [comptime](https://ziglang.org/documentation/master/#comptime).
            ,
            .parameters = &.{
                .{
                    .signature = "enum_or_tagged_union: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@intFromError",
        .{
            .return_type = "@Int(.unsigned, @bitSizeOf(anyerror))",
            .documentation =
            \\Supports the following types:
            \\
            \\ - [The Global Error Set](https://ziglang.org/documentation/master/#The-Global-Error-Set)
            \\ - [Error Set Type](https://ziglang.org/documentation/master/#Error-Set-Type)
            \\ - [Error Union Type](https://ziglang.org/documentation/master/#Error-Union-Type)
            \\Converts an error to the integer representation of an error.
            \\
            \\It is generally recommended to avoid this cast, as the integer representation of an error is not stable across source code changes.
            ,
            .parameters = &.{
                .{
                    .signature = "err: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@intFromFloat",
        .{
            .return_type = "anytype",
            .documentation =
            \\Deprecated. Equivalent to [@trunc](https://ziglang.org/documentation/master/#trunc).
            ,
            .parameters = &.{
                .{
                    .signature = "float: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@intFromPtr",
        .{
            .return_type = "usize",
            .documentation =
            \\Converts `value` to a `usize` which is the address of the pointer. `value` can be `*T` or `?*T`.
            \\
            \\To convert the other way, use [@ptrFromInt](https://ziglang.org/documentation/master/#ptrFromInt)
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@max",
        .{
            .return_type = "T",
            .documentation =
            \\Takes two or more arguments and returns the biggest value included (the maximum). This builtin accepts integers, floats, and vectors of either. In the latter case, the operation is performed element wise.
            \\
            \\NaNs are handled as follows: return the biggest non-NaN value included. If all operands are NaN, return NaN.
            ,
            .parameters = &.{
                .{
                    .signature = "...",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@memcpy",
        .{
            .return_type = "void",
            .documentation =
            \\This function copies bytes from one region of memory to another.
            \\
            \\`dest` must be a mutable slice, a mutable pointer to an array, or a mutable many-item [pointer](https://ziglang.org/documentation/master/#Pointers). It may have any alignment, and it may have any element type.
            \\
            \\`source` must be a slice, a pointer to an array, or a many-item [pointer](https://ziglang.org/documentation/master/#Pointers). It may have any alignment, and it may have any element type.
            \\
            \\The `source` element type must have the same in-memory representation as the `dest` element type.
            \\
            \\Similar to [for](https://ziglang.org/documentation/master/#for) loops, at least one of `source` and `dest` must provide a length, and if two lengths are provided, they must be equal.
            \\
            \\Finally, the two memory regions must not overlap.
            ,
            .parameters = &.{
                .{
                    .signature = "noalias dest",
                    .documentation = null,
                },
                .{
                    .signature = "noalias source",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@memset",
        .{
            .return_type = "void",
            .documentation =
            \\This function sets all the elements of a memory region to `elem`.
            \\
            \\`dest` must be a mutable slice or a mutable pointer to an array. It may have any alignment, and it may have any element type.
            \\
            \\`elem` is coerced to the element type of `dest`.
            \\
            \\For securely zeroing out sensitive contents from memory, you should use `std.crypto.secureZero`
            ,
            .parameters = &.{
                .{
                    .signature = "dest",
                    .documentation = null,
                },
                .{
                    .signature = "elem",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@memmove",
        .{
            .return_type = "void",
            .documentation =
            \\This function copies bytes from one region of memory to another, but unlike [@memcpy](https://ziglang.org/documentation/master/#memcpy) the regions may overlap.
            \\
            \\`dest` must be a mutable slice, a mutable pointer to an array, or a mutable many-item [pointer](https://ziglang.org/documentation/master/#Pointers). It may have any alignment, and it may have any element type.
            \\
            \\`source` must be a slice, a pointer to an array, or a many-item [pointer](https://ziglang.org/documentation/master/#Pointers). It may have any alignment, and it may have any element type.
            \\
            \\The `source` element type must have the same in-memory representation as the `dest` element type.
            \\
            \\Similar to [for](https://ziglang.org/documentation/master/#for) loops, at least one of `source` and `dest` must provide a length, and if two lengths are provided, they must be equal.
            ,
            .parameters = &.{
                .{
                    .signature = "dest",
                    .documentation = null,
                },
                .{
                    .signature = "source",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@min",
        .{
            .return_type = "T",
            .documentation =
            \\Takes two or more arguments and returns the smallest value included (the minimum). This builtin accepts integers, floats, and vectors of either. In the latter case, the operation is performed element wise.
            \\
            \\NaNs are handled as follows: return the smallest non-NaN value included. If all operands are NaN, return NaN.
            ,
            .parameters = &.{
                .{
                    .signature = "...",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@wasmMemorySize",
        .{
            .return_type = "usize",
            .documentation =
            \\This function returns the size of the Wasm memory identified by `index` as an unsigned value in units of Wasm pages. Note that each Wasm page is 64KB in size.
            \\
            \\This function is a low level intrinsic with no safety mechanisms usually useful for allocator designers targeting Wasm. So unless you are writing a new allocator from scratch, you should use something like `@import("std").heap.WasmPageAllocator`.
            ,
            .parameters = &.{
                .{
                    .signature = "index: u32",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@wasmMemoryGrow",
        .{
            .return_type = "isize",
            .documentation =
            \\This function increases the size of the Wasm memory identified by `index` by `delta` in units of unsigned number of Wasm pages. Note that each Wasm page is 64KB in size. On success, returns previous memory size; on failure, if the allocation fails, returns -1.
            \\
            \\This function is a low level intrinsic with no safety mechanisms usually useful for allocator designers targeting Wasm. So unless you are writing a new allocator from scratch, you should use something like `@import("std").heap.WasmPageAllocator`.
            ,
            .parameters = &.{
                .{
                    .signature = "index: u32",
                    .documentation = null,
                },
                .{
                    .signature = "delta: usize",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@mod",
        .{
            .return_type = "T",
            .documentation =
            \\Modulus division. For unsigned integers this is the same as `numerator % denominator`. Caller guarantees `denominator != 0`, otherwise the operation will result in a [Remainder Division by Zero](https://ziglang.org/documentation/master/#Remainder-Division-by-Zero) when runtime safety checks are enabled.
            \\
            \\ - `@mod(-5, 3) == 1`
            \\ - `(@divFloor(a, b) * b) + @mod(a, b) == a`
            \\For a function that returns an error code, see `@import("std").math.mod`.
            ,
            .parameters = &.{
                .{
                    .signature = "numerator: T",
                    .documentation = null,
                },
                .{
                    .signature = "denominator: T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@mulWithOverflow",
        .{
            .return_type = "struct { @TypeOf(a, b), u1 }",
            .documentation =
            \\Performs `a * b` and returns a tuple with the result and a possible overflow bit.
            ,
            .parameters = &.{
                .{
                    .signature = "a: anytype",
                    .documentation = null,
                },
                .{
                    .signature = "b: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@panic",
        .{
            .return_type = "noreturn",
            .documentation =
            \\Invokes the panic handler function. By default the panic handler function calls the public `panic` function exposed in the root source file, or if there is not one specified, the `std.lang.default_panic` function from `std/lang.zig`.
            \\
            \\Generally it is better to use `@import("std").debug.panic`. However, `@panic` can be useful for 2 scenarios:
            \\
            \\ - From library code, calling the programmer's panic function if they exposed one in the root source file.
            \\ - When mixing C and Zig code, calling the canonical panic implementation across multiple .o files.
            ,
            .parameters = &.{
                .{
                    .signature = "message: []const u8",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@popCount",
        .{
            .return_type = "anytype",
            .documentation =
            \\`@TypeOf(operand)` must be an integer type.
            \\
            \\`operand` may be an [integer](https://ziglang.org/documentation/master/#Integers) or [vector](https://ziglang.org/documentation/master/#Vectors).
            \\
            \\Counts the number of bits set in an integer - "population count".
            \\
            \\The return type is an unsigned integer or vector of unsigned integers with the minimum number of bits that can represent the bit count of the integer type.
            ,
            .parameters = &.{
                .{
                    .signature = "operand: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@prefetch",
        .{
            .return_type = "void",
            .documentation =
            \\This builtin tells the compiler to emit a prefetch instruction if supported by the target CPU. If the target CPU does not support the requested prefetch instruction, this builtin is a no-op. This function has no effect on the behavior of the program, only on the performance characteristics.
            \\
            \\The `ptr` argument may be any pointer type and determines the memory address to prefetch. This function does not dereference the pointer, it is perfectly legal to pass a pointer to invalid memory to this function and no Illegal Behavior will result.
            \\
            \\`PrefetchOptions` can be found with `@import("std").lang.PrefetchOptions`.
            ,
            .parameters = &.{
                .{
                    .signature = "ptr: anytype",
                    .documentation = null,
                },
                .{
                    .signature = "comptime options: PrefetchOptions",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@ptrCast",
        .{
            .return_type = "anytype",
            .documentation =
            \\Converts a pointer of one type to a pointer of another type. The return type is the inferred result type.
            \\
            \\[Optional Pointers](https://ziglang.org/documentation/master/#Optional-Pointers) are allowed. Casting an optional pointer which is [null](https://ziglang.org/documentation/master/#null) to a non-optional pointer invokes safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            \\
            \\`@ptrCast` cannot be used for:
            \\
            \\ - Removing `const` qualifier, use [@constCast](https://ziglang.org/documentation/master/#constCast).
            \\ - Removing `volatile` qualifier, use [@volatileCast](https://ziglang.org/documentation/master/#volatileCast).
            \\ - Changing pointer address space, use [@addrSpaceCast](https://ziglang.org/documentation/master/#addrSpaceCast).
            \\ - Increasing pointer alignment, use [@alignCast](https://ziglang.org/documentation/master/#alignCast).
            \\ - Casting a non-slice pointer to a slice, use slicing syntax `ptr[start..end]`.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@ptrFromInt",
        .{
            .return_type = "anytype",
            .documentation =
            \\Converts an integer to a [pointer](https://ziglang.org/documentation/master/#Pointers). The return type is the inferred result type. To convert the other way, use [@intFromPtr](https://ziglang.org/documentation/master/#intFromPtr). Casting an address of 0 to a destination type which in not [optional](https://ziglang.org/documentation/master/#Optional-Pointers) and does not have the `allowzero` attribute will result in a [Pointer Cast Invalid Null](https://ziglang.org/documentation/master/#Pointer-Cast-Invalid-Null) panic when runtime safety checks are enabled.
            \\
            \\If the destination pointer type does not allow address zero and `address` is zero, this invokes safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "address: usize",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@rem",
        .{
            .return_type = "T",
            .documentation =
            \\Remainder division. For unsigned integers this is the same as `numerator % denominator`. Caller guarantees `denominator != 0`, otherwise the operation will result in a [Remainder Division by Zero](https://ziglang.org/documentation/master/#Remainder-Division-by-Zero) when runtime safety checks are enabled.
            \\
            \\ - `@rem(-5, 3) == -2`
            \\ - `(@divTrunc(a, b) * b) + @rem(a, b) == a`
            \\For a function that returns an error code, see `@import("std").math.rem`.
            ,
            .parameters = &.{
                .{
                    .signature = "numerator: T",
                    .documentation = null,
                },
                .{
                    .signature = "denominator: T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@returnAddress",
        .{
            .return_type = "usize",
            .documentation =
            \\This function returns the address of the next machine code instruction that will be executed when the current function returns.
            \\
            \\The implications of this are target-specific and not consistent across all platforms.
            \\
            \\This function is only valid within function scope. If the function gets inlined into a calling function, the returned address will apply to the calling function.
            ,
            .parameters = &.{},
        },
    },
    .{
        "@select",
        .{
            .return_type = "@Vector(len, T)",
            .documentation =
            \\Selects values element-wise from `a` or `b` based on `pred`. If `pred[i]` is `true`, the corresponding element in the result will be `a[i]` and otherwise `b[i]`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
                .{
                    .signature = "pred: @Vector(len, bool)",
                    .documentation = null,
                },
                .{
                    .signature = "a: @Vector(len, T)",
                    .documentation = null,
                },
                .{
                    .signature = "b: @Vector(len, T)",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@setEvalBranchQuota",
        .{
            .return_type = "void",
            .documentation =
            \\Increase the maximum number of backwards branches that compile-time code execution can use before giving up and making a compile error.
            \\
            \\If the `new_quota` is smaller than the default quota (`1000`) or a previously explicitly set quota, it is ignored.
            \\
            \\Example:
            \\
            \\Now we use `@setEvalBranchQuota`:
            ,
            .parameters = &.{
                .{
                    .signature = "comptime new_quota: u32",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@setFloatMode",
        .{
            .return_type = "void",
            .documentation =
            \\Changes the current scope's rules about how floating point operations are defined.
            \\
            \\ - `.strict` (default) - Floating point operations follow strict IEEE compliance.
            \\ - `.optimized` - Floating point operations may do all of the following:
            \\   - Assume the arguments and result are not NaN. Optimizations are required to retain legal behavior over NaNs, but the value of the result is undefined.
            \\   - Assume the arguments and result are not +/-Inf. Optimizations are required to retain legal behavior over +/-Inf, but the value of the result is undefined.
            \\   - Treat the sign of a zero argument or result as insignificant.
            \\   - Use the reciprocal of an argument rather than perform division.
            \\   - Perform floating-point contraction (e.g. fusing a multiply followed by an addition into a fused multiply-add).
            \\   - Perform algebraically equivalent transformations that may change results in floating point (e.g. reassociate).
            \\This is equivalent to
            \\`-ffast-math`in GCC.
            \\The floating point mode is inherited by child scopes, and can be overridden in any scope. You can set the floating point mode in a struct or module scope by using a comptime block.
            \\
            \\`FloatMode` can be found with `@import("std").lang.FloatMode`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime mode: FloatMode",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@setRuntimeSafety",
        .{
            .return_type = "void",
            .documentation =
            \\Sets whether runtime safety checks are enabled for the scope that contains the function call.
            \\
            \\Note: it is
            \\[planned](https://github.com/ziglang/zig/issues/978)to replace `@setRuntimeSafety` with
            \\`@optimizeFor`
            ,
            .parameters = &.{
                .{
                    .signature = "comptime safety_on: bool",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@shlExact",
        .{
            .return_type = "T",
            .documentation =
            \\`). For unsigned integers, the result is [undefined](https://ziglang.org/documentation/master/#undefined) if any 1 bits are shifted out. For signed integers, the result is [undefined](https://ziglang.org/documentation/master/#undefined) if any bits that disagree with the resultant sign bit are shifted out.
            \\
            \\The type of `shift_amt` is an unsigned integer with `log2(@typeInfo(T).int.bits)` bits. This is because `shift_amt >= @typeInfo(T).int.bits` triggers safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            \\
            \\`comptime_int` is modeled as an integer with an infinite number of bits, meaning that in such case, `@shlExact` always produces a result and cannot produce a compile error.
            ,
            .parameters = &.{
                .{
                    .signature = "value: T",
                    .documentation = null,
                },
                .{
                    .signature = "shift_amt: Log2T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@shlWithOverflow",
        .{
            .return_type = "struct { @TypeOf(a), u1 }",
            .documentation =
            \\b` and returns a tuple with the result and a possible overflow bit.
            \\
            \\The type of `shift_amt` is an unsigned integer with `log2(@typeInfo(@TypeOf(a)).int.bits)` bits. This is because `shift_amt >= @typeInfo(@TypeOf(a)).int.bits` triggers safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "a: anytype",
                    .documentation = null,
                },
                .{
                    .signature = "shift_amt: Log2T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@shrExact",
        .{
            .return_type = "T",
            .documentation =
            \\Performs the right shift operation (`>>`). Caller guarantees that the shift will not shift any 1 bits out.
            \\
            \\The type of `shift_amt` is an unsigned integer with `log2(@typeInfo(T).int.bits)` bits. This is because `shift_amt >= @typeInfo(T).int.bits` triggers safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "value: T",
                    .documentation = null,
                },
                .{
                    .signature = "shift_amt: Log2T",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@shuffle",
        .{
            .return_type = "@Vector(mask_len, E)",
            .documentation =
            \\Constructs a new [vector](https://ziglang.org/documentation/master/#Vectors) by selecting elements from `a` and `b` based on `mask`.
            \\
            \\Each element in `mask` selects an element from either `a` or `b`. Positive numbers select from `a` starting at 0. Negative values select from `b`, starting at `-1` and going down. It is recommended to use the `~` operator for indexes from `b` so that both indexes can start from `0` (i.e. `~@as(i32, 0)` is `-1`).
            \\
            \\For each element of `mask`, if it or the selected value from `a` or `b` is `undefined`, then the resulting element is `undefined`.
            \\
            \\`a_len` and `b_len` may differ in length. Out-of-bounds element indexes in `mask` result in compile errors.
            \\
            \\If `a` or `b` is `undefined`, it is equivalent to a vector of all `undefined` with the same length as the other vector. If both vectors are `undefined`, `@shuffle` returns a vector with all elements `undefined`.
            \\
            \\`E` must be an [integer](https://ziglang.org/documentation/master/#Integers), [float](https://ziglang.org/documentation/master/#Floats), [pointer](https://ziglang.org/documentation/master/#Pointers), or `bool`. The mask may be any vector length, and its length determines the result length.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime E: type",
                    .documentation = null,
                },
                .{
                    .signature = "a: @Vector(a_len, E)",
                    .documentation = null,
                },
                .{
                    .signature = "b: @Vector(b_len, E)",
                    .documentation = null,
                },
                .{
                    .signature = "comptime mask: @Vector(mask_len, i32)",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@sizeOf",
        .{
            .return_type = "comptime_int",
            .documentation =
            \\This function returns the number of bytes it takes to store `T` in memory. The result is a target-specific compile time constant.
            \\
            \\This size may contain padding bytes. If there were two consecutive T in memory, the padding would be the offset in bytes between element at index 0 and the element at index 1. For [integer](https://ziglang.org/documentation/master/#Integers), consider whether you want to use `@sizeOf(T)` or `@typeInfo(T).int.bits`.
            \\
            \\This function measures the size at runtime. For types that are disallowed at runtime, such as `comptime_int` and `type`, the result is `0`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@splat",
        .{
            .return_type = "anytype",
            .documentation =
            \\Produces an array or vector where each element is the value `scalar`. The return type and thus the length of the vector is inferred.
            \\
            \\`scalar` must be an [integer](https://ziglang.org/documentation/master/#Integers), [bool](https://ziglang.org/documentation/master/#Primitive-Types), [float](https://ziglang.org/documentation/master/#Floats), or [pointer](https://ziglang.org/documentation/master/#Pointers).
            ,
            .parameters = &.{
                .{
                    .signature = "scalar: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@reduce",
        .{
            .return_type = "E",
            .documentation =
            \\Transforms a [vector](https://ziglang.org/documentation/master/#Vectors) into a scalar value (of type
            \\`E`) by performing a sequential horizontal reduction of its elements using the specified operator `op`.
            \\
            \\Not every operator is available for every vector element type:
            \\
            \\ - Every operator is available for [integer](https://ziglang.org/documentation/master/#Integers) vectors.
            \\ - `.And`, `.Or`, `.Xor` are additionally available for `bool` vectors,
            \\ - `.Min`, `.Max`, `.Add`, `.Mul` are additionally available for [floating point](https://ziglang.org/documentation/master/#Floats) vectors,
            \\Note that `.Add` and `.Mul` reductions on integral types are wrapping; when applied on floating point types the operation associativity is preserved, unless the float mode is set to `.optimized`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime op: ReduceOp",
                    .documentation = null,
                },
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@src",
        .{
            .return_type = "SourceLocation",
            .documentation =
            \\Returns a `SourceLocation` struct representing the function's name and location in the source code. This must be called in a function.
            ,
            .parameters = &.{},
        },
    },
    .{
        "@sqrt",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Performs the square root of a floating point number. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@sin",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Sine trigonometric function on a floating point number in radians. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@cos",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Cosine trigonometric function on a floating point number in radians. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@tan",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Tangent trigonometric function on a floating point number in radians. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@exp",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Base-e exponential function on a floating point number. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@exp2",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Base-2 exponential function on a floating point number. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@log",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Returns the natural logarithm of a floating point number. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@log2",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Returns the logarithm to the base 2 of a floating point number. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@log10",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Returns the logarithm to the base 10 of a floating point number. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@abs",
        .{
            .return_type = "anytype",
            .documentation =
            \\Returns the absolute value of an integer or a floating point number. Uses a dedicated hardware instruction when available.  The return type is always an unsigned integer of the same bit width as the operand if the operand is an integer. Unsigned integer operands are supported. The builtin cannot overflow for signed integer operands.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats), [Integers](https://ziglang.org/documentation/master/#Integers) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats or integers.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@floor",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Returns the largest integral value not greater than the given floating point number. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            \\
            \\When the inferred result type is an [integer](https://ziglang.org/documentation/master/#Integers), the integer part is extracted from the floored result. If that value cannot fit in the destination type, it invokes safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@ceil",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Returns the smallest integral value not less than the given floating point number. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            \\
            \\When the inferred result type is an [integer](https://ziglang.org/documentation/master/#Integers), the integer part is extracted from the ceiled result. If that value cannot fit in the destination type, it invokes safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@trunc",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Rounds the given floating point number to an integer, towards zero. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of float parameters.
            \\
            \\When the inferred result type is an [integer](https://ziglang.org/documentation/master/#Integers), the integer part is extracted from the truncated result. If that value cannot fit in the destination type, it invokes safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@round",
        .{
            .return_type = "@TypeOf(value)",
            .documentation =
            \\Rounds the given floating point number to the nearest integer. If two integers are equally close, rounds away from zero. Uses a dedicated hardware instruction when available.
            \\
            \\Supports [Floats](https://ziglang.org/documentation/master/#Floats) and [Vectors](https://ziglang.org/documentation/master/#Vectors) of floats.
            \\
            \\When the inferred result type is an [integer](https://ziglang.org/documentation/master/#Integers), the integer part is extracted from the rounded result. If that value cannot fit in the destination type, it invokes safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@subWithOverflow",
        .{
            .return_type = "struct { @TypeOf(a, b), u1 }",
            .documentation =
            \\Performs `a - b` and returns a tuple with the result and a possible overflow bit.
            ,
            .parameters = &.{
                .{
                    .signature = "a: anytype",
                    .documentation = null,
                },
                .{
                    .signature = "b: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@tagName",
        .{
            .return_type = "[:0]const u8",
            .documentation =
            \\Converts an enum value or union value to a string literal representing the name.
            \\
            \\If the enum is non-exhaustive and the tag value does not map to a name, it invokes safety-checked [Illegal Behavior](https://ziglang.org/documentation/master/#Illegal-Behavior).
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@This",
        .{
            .return_type = "type",
            .documentation =
            \\Returns the innermost struct, enum, or union that this function call is inside. This can be useful for an anonymous struct that needs to refer to itself:
            \\
            \\When `@This()` is used at file scope, it returns a reference to the struct that corresponds to the current file.
            ,
            .parameters = &.{},
        },
    },
    .{
        "@trap",
        .{
            .return_type = "noreturn",
            .documentation =
            \\This function inserts a platform-specific trap/jam instruction which can be used to exit the program abnormally. This may be implemented by explicitly emitting an invalid instruction which may cause an illegal instruction exception of some sort. Unlike for `@breakpoint()`, execution does not continue after this point.
            \\
            \\Outside function scope, this builtin causes a compile error.
            ,
            .parameters = &.{},
        },
    },
    .{
        "@truncate",
        .{
            .return_type = "anytype",
            .documentation =
            \\This function truncates bits from an integer type, resulting in a smaller or same-sized integer type. The return type is the inferred result type.
            \\
            \\This function always truncates the significant bits of the integer, regardless of endianness on the target platform.
            \\
            \\Calling `@truncate` on a number out of range of the destination type is well defined and working code:
            \\
            \\Use [@intCast](https://ziglang.org/documentation/master/#intCast) to convert numbers guaranteed to fit the destination type.
            ,
            .parameters = &.{
                .{
                    .signature = "integer: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@EnumLiteral",
        .{
            .return_type = "type",
            .documentation =
            \\Returns the comptime-only "enum literal" type. This is the type of uncoerced [Enum Literals](https://ziglang.org/documentation/master/#Enum-Literals). Values of this type can coerce to any [enum](https://ziglang.org/documentation/master/#enum) with a matching field.
            ,
            .parameters = &.{},
        },
    },
    .{
        "@Int",
        .{
            .return_type = "type",
            .documentation =
            \\Returns an integer type with the given signedness and bit width.
            \\
            \\For instance, `@Int(.unsigned, 18)` returns the type `u18`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime signedness: Signedness",
                    .documentation = null,
                },
                .{
                    .signature = "comptime bits: u16",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@Tuple",
        .{
            .return_type = "type",
            .documentation =
            \\Returns a [tuple](https://ziglang.org/documentation/master/#Tuples) type with the given field types.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime field_types: []const type",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@Pointer",
        .{
            .return_type = "type",
            .documentation =
            \\Returns a [pointer](https://ziglang.org/documentation/master/#Pointers) type with the properties specified by the arguments.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime size: Type.Pointer.Size",
                    .documentation = null,
                },
                .{
                    .signature = "comptime attrs: Type.Pointer.Attributes",
                    .documentation = null,
                },
                .{
                    .signature = "comptime Element: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime sentinel: ?Element",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@Fn",
        .{
            .return_type = "type",
            .documentation =
            \\Returns a [function](https://ziglang.org/documentation/master/#Functions) type with the properties specified by the arguments.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime param_types: []const type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime param_attrs: *const [param_types.len]Type.Fn.Param.Attributes",
                    .documentation = null,
                },
                .{
                    .signature = "comptime ReturnType: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime attrs: Type.Fn.Attributes",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@Struct",
        .{
            .return_type = "type",
            .documentation =
            \\Returns a [struct](https://ziglang.org/documentation/master/#struct) type with the properties specified by the arguments.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime layout: Type.ContainerLayout",
                    .documentation = null,
                },
                .{
                    .signature = "comptime BackingInt: ?type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_names: []const []const u8",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_types: *const [field_names.len]type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_attrs: *const [field_names.len]Type.StructField.Attributes",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@Union",
        .{
            .return_type = "type",
            .documentation =
            \\Returns a [union](https://ziglang.org/documentation/master/#union) type with the properties specified by the arguments.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime layout: Type.ContainerLayout",
                    .documentation = null,
                },
                .{
                    .signature = "comptime ArgType: ?type",
                    .documentation = " Either the integer tag type, or the integer backing type, depending on `layout`.\n",
                },
                .{
                    .signature = "comptime field_names: []const []const u8",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_types: *const [field_names.len]type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_attrs: *const [field_names.len]Type.UnionField.Attributes",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@Enum",
        .{
            .return_type = "type",
            .documentation =
            \\Returns an [enum](https://ziglang.org/documentation/master/#enum) type with the properties specified by the arguments.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime TagInt: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime mode: Type.Enum.Mode",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_names: []const []const u8",
                    .documentation = null,
                },
                .{
                    .signature = "comptime field_values: *const [field_names.len]TagInt",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@typeInfo",
        .{
            .return_type = "Type",
            .documentation =
            \\Provides type reflection.
            \\
            \\Type information of [structs](https://ziglang.org/documentation/master/#struct), [unions](https://ziglang.org/documentation/master/#union), [enums](https://ziglang.org/documentation/master/#enum), and [error sets](https://ziglang.org/documentation/master/#Error-Set-Type) has fields which are guaranteed to be in the same order as appearance in the source file.
            \\
            \\Type information of [structs](https://ziglang.org/documentation/master/#struct), [unions](https://ziglang.org/documentation/master/#union), [enums](https://ziglang.org/documentation/master/#enum), and [opaques](https://ziglang.org/documentation/master/#opaque) has declarations, which are also guaranteed to be in the same order as appearance in the source file.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime T: type",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@typeName",
        .{
            .return_type = "*const [N:0]u8",
            .documentation =
            \\This function returns the string representation of a type, as an array. It is equivalent to a string literal of the type name. The returned type name is fully qualified with the parent namespace included as part of the type name with a series of dots.
            ,
            .parameters = &.{
                .{
                    .signature = "T: type",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@TypeOf",
        .{
            .return_type = "type",
            .documentation =
            \\`@TypeOf` is a special builtin function that takes any (non-zero) number of expressions as parameters and returns the type of the result, using [Peer Type Resolution](https://ziglang.org/documentation/master/#Peer-Type-Resolution).
            \\
            \\The expressions are evaluated, however they are guaranteed to have no
            \\**runtime** side-effects:
            ,
            .parameters = &.{
                .{
                    .signature = "...",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@unionInit",
        .{
            .return_type = "Union",
            .documentation =
            \\This is the same thing as [union](https://ziglang.org/documentation/master/#union) initialization syntax, except that the field name is a [comptime](https://ziglang.org/documentation/master/#comptime)-known value rather than an identifier token.
            \\
            \\`@unionInit` forwards its [result location](https://ziglang.org/documentation/master/#Result-Location-Semantics) to `init_expr`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime Union: type",
                    .documentation = null,
                },
                .{
                    .signature = "comptime active_field_name: []const u8",
                    .documentation = null,
                },
                .{
                    .signature = "init_expr",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@Vector",
        .{
            .return_type = "type",
            .documentation =
            \\Creates [Vectors](https://ziglang.org/documentation/master/#Vectors).
            ,
            .parameters = &.{
                .{
                    .signature = "len: comptime_int",
                    .documentation = null,
                },
                .{
                    .signature = "Element: type",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@volatileCast",
        .{
            .return_type = "DestType",
            .documentation =
            \\Remove `volatile` qualifier from a pointer.
            ,
            .parameters = &.{
                .{
                    .signature = "value: anytype",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@workGroupId",
        .{
            .return_type = "u32",
            .documentation =
            \\Returns the index of the work group in the current kernel invocation in dimension `dimension`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime dimension: u32",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@workGroupSize",
        .{
            .return_type = "u32",
            .documentation =
            \\Returns the number of work items that a work group has in dimension `dimension`.
            ,
            .parameters = &.{
                .{
                    .signature = "comptime dimension: u32",
                    .documentation = null,
                },
            },
        },
    },
    .{
        "@workItemId",
        .{
            .return_type = "u32",
            .documentation =
            \\Returns the index of the work item in the work group in dimension `dimension`. This function returns values between `0` (inclusive) and `@workGroupSize(dimension)` (exclusive).
            ,
            .parameters = &.{
                .{
                    .signature = "comptime dimension: u32",
                    .documentation = null,
                },
            },
        },
    },
});

// DO NOT EDIT
