name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.17.0-dev.93+76174e1bc
      - run: zig build test --summary all
      - run: zig build -Doptimize=ReleaseFast
